import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { firestore } from '../firebase/firebase';
import {
    collection,
    DocumentData,
    getDocs,
    query,
    QueryDocumentSnapshot,
} from 'firebase/firestore';
import styles from '../styles/Home.module.css';

export default function Home() {
    const [clients, setClients] = useState<Array<Object>>();
    const [isLoaded, setIsLoaded] = useState<boolean>(false);

    const clientsCollection = collection(firestore, 'clients');

    const getClientsData = async () => {
        const canvasQuery = query(clientsCollection);
        const querySnapshot = await getDocs(canvasQuery);

        const result: QueryDocumentSnapshot<DocumentData>[] = [];

        querySnapshot.forEach((snapshot) => {
            result.push(snapshot);
        });

        setClients(
            result.map((client) => ({
                id: client.id,
                firstName: client.data().firstName,
                lastName: client.data().lastName,
            }))
        );

        setIsLoaded(true);
    };

    useEffect(() => {
        getClientsData();
        console.log(clients);
    }, []);

    const clientsList = clients?.map((client) => {
        return (
            <p>
                {client.firstName} {client.lastName}
            </p>
        );
    });

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                {isLoaded ? clientsList : null}
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
