export declare type Client = {
    readonly id: string;
    readonly notes?: string | null;
    readonly gender?: string | null;
    readonly numKids?: string | null;
    readonly birthday?: string | null;
    readonly isBanned?: string | null;
    readonly lastName?: string | null;
    readonly firstName?: string | null;
    readonly lastNameLower?: string | null;
    readonly firstNameLower?: string | null;
    readonly createdAt?: string | null;
    readonly lastUpdate?: string | null;
    readonly postalCode?: string | null;
    readonly isCheckedIn?: string | null;
    readonly numInFamily?: string | null;
    readonly lastBackpack?: string | null;
    readonly lastBusTicket?: string | null;
    readonly middleInitial?: string | null;
    readonly lastSleepingbag?: string | null;
    readonly BerthaPittsCampbellResident?: string | null;
    readonly lastFinancialAssistanceDate?: string | null;
    readonly lastFinancialAssistanceValue?: string | null;
};

export declare type Visit = {
    readonly id: string;
    readonly kids?: string | null;
    readonly mens?: string | null;
    readonly soap?: string | null;
    readonly kidsQ?: string | null;
    readonly mensQ?: string | null;
    readonly notes?: string | null;
    readonly oldID?: string | null;
    readonly razor?: string | null;
    readonly boyAge?: string | null;
    readonly diaper?: string | null;
    readonly lotion?: string | null;
    readonly womens?: string | null;
    readonly girlAge?: string | null;
    readonly womensQ?: string | null;
    readonly backpack?: string | null;
    readonly giftCard?: string | null;
    readonly busTicket?: string | null;
    readonly household?: string | null;
    readonly timestamp?: string | null;
    readonly toothbrush?: string | null;
    readonly toothpaste?: string | null;
    readonly clothingBoy?: string | null;
    readonly clothingMen?: string | null;
    readonly sleepingBag?: string | null;
    readonly clothingGirl?: string | null;
    readonly lastBackpack?: string | null;
    readonly clothingWomen?: string | null;
    readonly lastSleepingBag?: string | null;
    readonly shampooConditioner?: string | null;
    readonly financialAssistance?: string | null;
    readonly lastFinancialAssistance?: string | null;
};
